version: 2
updates:
  # Maintain GitHub Action dependencies.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain docker dependencies.
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
